name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the required Python version

      - name: Install dependencies
        run: |
          bundle install
          python -m venv path/to/venv
          source path/to/venv/bin/activate
          pip install -r requirements.txt  # If you have a requirements file

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
